seed: 0
device: cpu

env:
  max_length: 7

oracle:
  budget: 1000
  vocabulary_check: true

metrics:
  # If known, set to the true environment optimum for true regret computation
  optimum_score: null

dataset:
  num_queries: 1000
  unique: false

logging:
  output_dir: outputs

hydra:
  run:
    dir: ${logging.output_dir}/dataset/${now:%Y-%m-%d_%H-%M-%S}_seed${seed}
  job:
    chdir: false
