seed: 0
device: cpu
float_precision: 32
gflownet_root: ../gflownet

env:
  max_length: 7
  num_tokens: 27

oracle:
  budget: 1000
  vocabulary_check: true
  enforce_budget: true

metrics:
  optimum_score: 45

gflownet:
  n_train_steps: 250
  batch_size_forward: 4
  lr: 0.0001
  z_dim: 16
  lr_z_mult: 10.0
  random_action_prob: 0.08
  reward_min: 0.0
  do_clip_rewards: false
  evaluation_samples: 512
  policy:
    hidden_dim: 256
    n_layers: 3
    shared_backward: false
  evaluator:
    period: 250
    n: 128
    checkpoints_period: 250

logging:
  output_dir: outputs

hydra:
  run:
    dir: ${logging.output_dir}/gflownet/${now:%Y-%m-%d_%H-%M-%S}_seed${seed}
  job:
    chdir: false
